language: objective-c
osx_image: xcode7.1

script:
  - xcodebuild clean build test -project SwiftClient.xcodeproj -scheme SwiftClient -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
